let data = [
  {
    id: 1,
    image: './images/shirt-nike.jpg',
    name: 'Футболка Nike',
    text: 'Описание футболки Nike',
    data: '2023-05-01',
    type: 'shirt',
  },
  {
    id: 2,
    image: './images/shirt-adidas.jpg',
    name: 'Футболка Adidas',
    text: 'Описание футболки Adidas',
    data: '2023-05-02',
    type: 'shirt',
  },
  {
    id: 3,
    image: './images/shirt-puma.jpg',
    name: 'Футболка Puma',
    text: 'Описание футболки Puma',
    data: '2023-05-03',
    type: 'shirt',
  },
  {
    id: 4,
    image: './images/shirt-demix.jpg',
    name: 'Футболка Demix',
    text: 'Описание футболки Demix',
    data: '2023-05-04',
    type: 'shirt',
  },
  {
    id: 5,
    image: './images/pants-nike.jpg',
    name: 'Штаны Nike',
    text: 'Описание штанов Nike',
    data: '2023-05-05',
    type: 'pants',
  },
  {
    id: 6,
    image: './images/pants-adidas.jpg',
    name: 'Штаны Adidas',
    text: 'Описание штанов Adidas',
    data: '2023-05-06',
    type: 'pants',
  },
  {
    id: 7,
    image: './images/pants-puma.jpg',
    name: 'Штаны Puma',
    text: 'Описание штанов Puma',
    data: '2023-05-07',
    type: 'pants',
  },
  {
    id: 9,
    image: './images/pants-demix.jpg',
    name: 'Штаны Demix',
    text: 'Описание штанов Demix',
    data: '2023-05-08',
    type: 'pants',
  },
  {
    id: 10,
    image: './images/shoes-nike.jpg',
    name: 'Обувь Nike',
    text: 'Описание обуви Nike',
    data: '2023-05-09',
    type: 'shoes',
  },
  {
    id: 11,
    image: './images/shoes-adidas.jpg',
    name: 'Обувь Adidas',
    text: 'Описание обуви Adidas',
    data: '2023-05-10',
    type: 'shoes',
  },
  {
    id: 12,
    image: './images/shoes-puma.jpg',
    name: 'Обувь Puma',
    text: 'Описание обуви Puma',
    data: '2023-05-11',
    type: 'shoes',
  },
  {
    id: 13,
    image: './images/shoes-demix.jpg',
    name: 'Обувь Demix',
    text: 'Описание обуви Demix',
    data: '2023-05-12',
    type: 'shoes',
  },
  {
    id: 14,
    image: './images/shoes1.jpg',
    name: 'Обувь №1',
    text: 'Описание обуви №1',
    data: '2023-05-13',
    type: 'shoes',
  },
  {
    id: 15,
    image: './images/shoes2.jpg',
    name: 'Обувь №2',
    text: 'Описание обуви №2',
    data: '2023-05-14',
    type: 'shoes',
  },
  {
    id: 16,
    image: './images/shoes3.jpg',
    name: 'Обувь №3',
    text: 'Описание обуви №3',
    data: '2023-05-15',
    type: 'shoes',
  },
  {
    id: 17,
    image: './images/shoes4.jpg',
    name: 'Обувь №4',
    text: 'Описание обуви №4',
    data: '2023-05-16',
    type: 'shoes',
  },
  {
    id: 18,
    image: './images/shoes5.jpg',
    name: 'Обувь №5',
    text: 'Описание обуви №5',
    data: '2023-05-17',
    type: 'shoes',
  },
  {
    id: 19,
    image: './images/shoes6.jpg',
    name: 'Обувь №6',
    text: 'Описание обуви №6',
    data: '2023-05-18',
    type: 'shoes',
  },
  {
    id: 20,
    image: './images/pants1.jpg',
    name: 'Штаны №1',
    text: 'Описание штанов #1',
    data: '2023-05-19',
    type: 'pants',
  },
  {
    id: 21,
    image: './images/pants2.jpg',
    name: 'Штаны №2',
    text: 'Описание штанов #2',
    data: '2023-05-20',
    type: 'pants',
  },
  {
    id: 22,
    image: './images/pants3.jpg',
    name: 'Штаны №3',
    text: 'Описание штанов №3',
    data: '2023-05-21',
    type: 'pants',
  },
  {
    id: 23,
    image: './images/pants4.jpg',
    name: 'Штаны №4',
    text: 'Описание штанов №4',
    data: '2023-05-22',
    type: 'pants',
  },
  {
    id: 24,
    image: './images/pants5.jpg',
    name: 'Штаны №5',
    text: 'Описание штанов №5',
    data: '2023-05-23',
    type: 'pants',
  },
  {
    id: 25,
    image: './images/pants6.jpg',
    name: 'Штаны №6',
    text: 'Описание штанов №6',
    data: '2023-05-24',
    type: 'pants',
  },
  {
    id: 26,
    image: './images/shirt1.jpg',
    name: 'Футболка №1',
    text: 'Описание футболки №1',
    data: '2023-05-25',
    type: 'shirt',
  },
  {
    id: 27,
    image: './images/shirt2.jpg',
    name: 'Футболка №2',
    text: 'Описание футболки №2',
    data: '2023-05-26',
    type: 'shirt',
  },
  {
    id: 28,
    image: './images/shirt3.jpg',
    name: 'Футболка №3',
    text: 'Описание футболки №3',
    data: '2023-05-27',
    type: 'shirt',
  },
  {
    id: 29,
    image: './images/shirt4.jpg',
    name: 'Футболка №4',
    text: 'Описание футболки №4',
    data: '2023-05-28',
    type: 'shirt',
  },
  {
    id: 30,
    image: './images/shirt5.jpg',
    name: 'Футболка №5',
    text: 'Описание футболки №5',
    data: '2023-05-29',
    type: 'shirt',
  },
  {
    id: 31,
    image: './images/shirt6.jpg',
    name: 'Футболка №6',
    text: 'Описание футболки №6',
    data: '2023-05-30',
    type: 'shirt',
  },
];

export default data;
